const castingClassMaxLevels = (charClass, classLevel) => {
    switch (charClass) {
        case 'Consular':
            switch (classLevel) {
                case 1:
                    return 1
                case 2:
                    return 1
                case 3:
                    return 2
                case 4:
                    return 2
                case 5:
                    return 3
                case 6:
                    return 3
                case 7:
                    return 4
                case 8:
                    return 4
                case 9:
                    return 5
                case 10:
                    return 5
                case 11:
                    return 6
                case 12:
                    return 6
                case 13:
                    return 7
                case 14:
                    return 7
                case 15:
                    return 8
                case 16:
                    return 8
                case 17:
                    return 9
                case 18:
                    return 9
                case 19:
                    return 9
                case 20:
                    return 9
            }
        case 'Guardian':
            switch (classLevel) {
                case 1:
                    return 1
                case 2:
                    return 1
                case 3:
                    return 1
                case 4:
                    return 1
                case 5:
                    return 2
                case 6:
                    return 2
                case 7:
                    return 2
                case 8:
                    return 2
                case 9:
                    return 3
                case 10:
                    return 3
                case 11:
                    return 3
                case 12:
                    return 3
                case 13:
                    return 4
                case 14:
                    return 4
                case 15:
                    return 4
                case 16:
                    return 4
                case 17:
                    return 5
                case 18:
                    return 5
                case 19:
                    return 5
                case 20:
                    return 5
            }
        case 'Sentinel':
            switch (classLevel) {
                case 1:
                    return 1
                case 2:
                    return 1
                case 3:
                    return 2
                case 4:
                    return 2
                case 5:
                    return 2
                case 6:
                    return 3
                case 7:
                    return 3
                case 8:
                    return 3
                case 9:
                    return 4
                case 10:
                    return 4
                case 11:
                    return 5
                case 12:
                    return 5
                case 13:
                    return 5
                case 14:
                    return 6
                case 15:
                    return 6
                case 16:
                    return 6
                case 17:
                    return 7
                case 18:
                    return 7
                case 19:
                    return 7
                case 20:
                    return 7
            }
        case 'Engineer':
            switch (classLevel) {
                case 1:
                    return 1
                case 2:
                    return 1
                case 3:
                    return 2
                case 4:
                    return 2
                case 5:
                    return 3
                case 6:
                    return 3
                case 7:
                    return 4
                case 8:
                    return 4
                case 9:
                    return 5
                case 10:
                    return 5
                case 11:
                    return 6
                case 12:
                    return 6
                case 13:
                    return 7
                case 14:
                    return 7
                case 15:
                    return 8
                case 16:
                    return 8
                case 17:
                    return 9
                case 18:
                    return 9
                case 19:
                    return 9
                case 20:
                    return 9
            }
        case 'Scout':
            switch (classLevel) {
                case 1:
                    return 0
                case 2:
                    return 1
                case 3:
                    return 1
                case 4:
                    return 1
                case 5:
                    return 2
                case 6:
                    return 2
                case 7:
                    return 2
                case 8:
                    return 2
                case 9:
                    return 3
                case 10:
                    return 3
                case 11:
                    return 3
                case 12:
                    return 3
                case 13:
                    return 4
                case 14:
                    return 4
                case 15:
                    return 4
                case 16:
                    return 4
                case 17:
                    return 5
                case 18:
                    return 5
                case 19:
                    return 5
                case 20:
                    return 5
            }
    }
}

export default castingClassMaxLevels